### ISSUE TITLE
TypeError: Could not locate class 'Model'

### ISSUE THREAD

**Issue by hentaipenguin** [vbelz/Speech-enhancement#38]
I got this problem when trying to run the prediction, I ran with your model_unet from your weights folder

```
Traceback (most recent call last):
  File "D:\Speech-enhancement\main.py", line 105, in <module>
    prediction(weights_path, name_model, audio_dir_prediction, dir_save_prediction, audio_input_prediction,
  File "D:\Speech-enhancement\prediction_denoise.py", line 18, in prediction
    loaded_model = model_from_json(loaded_model_json)
  File "D:\Speech-enhancement\venv\lib\site-packages\keras\src\models\model.py", line 752, in model_from_json
    return serialization_lib.deserialize_keras_object(
  File "D:\Speech-enhancement\venv\lib\site-packages\keras\src\saving\serialization_lib.py", line 694, in deserialize_keras_object    
    cls = _retrieve_class_or_fn(
  File "D:\Speech-enhancement\venv\lib\site-packages\keras\src\saving\serialization_lib.py", line 812, in _retrieve_class_or_fn       
    raise TypeError(
TypeError: Could not locate class 'Model'. Make sure custom classes are decorated with `@keras.saving.register_keras_serializable()`
```

**Comment by hentaipenguin** [comment]
`pip install tensorflow==2.13.0`

this worked for me, try install previous version for compatibility~
